### ISSUE TITLE
Cannot find module './build/Release/shell' with v0.3.1

### ISSUE THREAD

**Issue by nwinkler** [cri5ti/grunt-shell-spawn#29] opened 2015-01-08 09:13 UTC
After updating to v0.3.1, I'm getting the following error when running the shell task:

```
Cannot find module './build/Release/shell'
```

Here's the respective configuration from my `Grunfile.js`:

```
        shell: {
            xvfb: {
                command: 'Xvfb :99 -ac -screen 0 1600x1200x24',
                options: {
                    async: true
                }
            }
        }
```

Do I need to update my configuration when using v0.3.1? Reverting to v0.3.0 fixes the issue immediately.

**Comment by nwinkler** [comment] 2015-01-08 09:14
Is this caused by the change in #18?

**Comment by ValentinH** [comment] 2015-01-12 15:53
:thumbsup: same here

**Comment by utkukaratas** [comment] 2015-01-26 18:25
seconded. 0.3.0 seems to work.

**Comment by ip2k** [comment] 2015-03-11 23:37
+1, this has broken our automated testing :<

**Comment by radutopala** [comment] 2015-03-17 13:28
:+1: same here, 0.3.0 works fine.

**Comment by dandv** [comment] 2015-05-01 05:46
Is this still a problem, or can we close?

**Comment by cri5ti** [comment] 2015-09-08 12:45
This issue seems to have been caused by the use of `execSync`, which has been replaced with `sync-exec` since 0.3.2. 
Closing the issue.

**Closed by cri5ti** 2015-09-08 12:45 UTC
